# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8c43e9db577915f178daebe006ae1e1dc3a2919669f3fe3cd1e72862df480fcec482d3ce6627fdb0e068efeef0f3811d85a312ea5449c5771df443a07e2c26

test:
  secret_key_base: df125c392ab94780b61504179d1921b4e7f5bec1c21eb194b6ecb3eafd29188d73493ad309cd0dde7b5e9945a0c740ff3d22e5ca98160dfa08f5595deca4fc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
